### ISSUE TITLE
JB!

### ISSUE THREAD

**Issue by darkdarcool** [GitAPI-it/GitAPI.it-Python#2]
When are you gonna work on dis?

**Comment by TheQuackyDuck** [comment]
ah shucks looks like he's not on.

**Comment by darkdarcool** [comment]
Time to ping @JBYT27

**Comment by JBYT27** [comment]
Lol
Hi @darkdarcool

**Comment by darkdarcool** [comment]
Is him

**Comment by darkdarcool** [comment]
So, when are you gonna work on this?

**Comment by JBYT27** [comment]
Well, I have other stuff to work on~~, and my screen time is limited lol~~, so prob when im completely free

**Comment by darkdarcool** [comment]
Very specific, thanks!

**Comment by TheQuackyDuck** [comment]
![image](https://user-images.githubusercontent.com/79815764/125202721-c0232f80-e229-11eb-856d-21ac94d67368.png)

Ha! dont edit it jb, ur not the only one who has their screen time limited, me too!!!

**Comment by JBYT27** [comment]
Lol i tried to cross out, didnt work xD
Lol rip

**Comment by darkdarcool** [comment]
LOL

**Comment by darkdarcool** [comment]
Mine is too, but coding doesn’t apply :)

**Comment by JBYT27** [comment]
oooooooo

**Comment by darkdarcool** [comment]
O
